In [1]:
!pip install tensorflow
!pip install tensorflow_hub
!pip install -q -U "tensorflow-text==2.13.*"
!pip install "tf-models-official==2.13.*"

  Obtaining dependency information for tf-models-official==2.13.* from https://files.pythonhosted.org/packages/d8/c3/4511e49412492966f4e6e0a20b41ae66d027e5a76e8c2b436b591ecc4273/tf_models_official-2.13.2-py2.py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 1.7 MB/s eta 0:00:00
  Obtaining dependency information for immutabledict from https://files.pythonhosted.org/packages/77/d8/69b89c358609ef1853d860bcf59472abe65e2c434767e6e91c57e12e5c23/immutabledict-4.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for pycocotools from https://files.pythonhosted.org/packages/ba/64/0451cf41a00fd5ac4501de4ea0e395b7d909e09d665e56890b5d3809ae26/pycocotools-2.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for sacrebleu from https://files.pythonhosted.org/packages/0a/a6/2ac47e71e526bbcd97ea08f20d9ef7d3852e2594ec7b2d55f5d2bbfd7aae/sacrebleu-2.3.3-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━

In [2]:
!pip install gdown

In [3]:
import tensorflow as tf
import gdown
import tensorflow_hub as hub
import tensorflow_text as text
import tensorflow as tf
import os

In [4]:
# unduh zip file
file_id = "1-jUsdSAEf5iUyR1ZGvvvRatE_vcETSjX"
output_file = "/kaggle/working/model_sn.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")

# unduh zip file
file_id = "1am-Q1f2YNMgNhIj2jV2WIMjhs1jRU1Zm"
output_file = "/kaggle/working/model_tf.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")

# unduh zip file
file_id = "1-OXvFKlgCUrU28IkBzzt1DAvMdVCY1T0"
output_file = "/kaggle/working/model_ei.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")

# unduh zip file
file_id = "1--fBI59iDhoW67XlevG8kH-vA-mb3lus"
output_file = "/kaggle/working/model_jp.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")
# https://drive.google.com/file/d/1-jUsdSAEf5iUyR1ZGvvvRatE_vcETSjX/view?usp=drive_link
# https://drive.google.com/file/d/1am-Q1f2YNMgNhIj2jV2WIMjhs1jRU1Zm/view?usp=sharing
# https://drive.google.com/file/d/1-OXvFKlgCUrU28IkBzzt1DAvMdVCY1T0/view?usp=sharing
# https://drive.google.com/file/d/1--fBI59iDhoW67XlevG8kH-vA-mb3lus/view?usp=sharing

Downloading...
From (uriginal): https://drive.google.com/uc?id=1-jUsdSAEf5iUyR1ZGvvvRatE_vcETSjX
From (redirected): https://drive.google.com/uc?id=1-jUsdSAEf5iUyR1ZGvvvRatE_vcETSjX&confirm=t&uuid=00794cdf-a35e-4c84-9c24-43f53294081d
To: /kaggle/working/model_sn.zip
100%|██████████| 666M/666M [00:03<00:00, 191MB/s]  


File berhasil diunduh ke  /kaggle/working/model_sn.zip


Downloading...
From (uriginal): https://drive.google.com/uc?id=1am-Q1f2YNMgNhIj2jV2WIMjhs1jRU1Zm
From (redirected): https://drive.google.com/uc?id=1am-Q1f2YNMgNhIj2jV2WIMjhs1jRU1Zm&confirm=t&uuid=f1e3c68b-62d9-4927-a56a-8947b2db94ac
To: /kaggle/working/model_tf.zip
100%|██████████| 664M/664M [00:03<00:00, 200MB/s]  


File berhasil diunduh ke  /kaggle/working/model_tf.zip


Downloading...
From (uriginal): https://drive.google.com/uc?id=1-OXvFKlgCUrU28IkBzzt1DAvMdVCY1T0
From (redirected): https://drive.google.com/uc?id=1-OXvFKlgCUrU28IkBzzt1DAvMdVCY1T0&confirm=t&uuid=fac727aa-dc0b-4ab9-ad6f-0c165243bc8e
To: /kaggle/working/model_ei.zip
100%|██████████| 665M/665M [00:07<00:00, 94.2MB/s] 


File berhasil diunduh ke  /kaggle/working/model_ei.zip


Downloading...
From (uriginal): https://drive.google.com/uc?id=1--fBI59iDhoW67XlevG8kH-vA-mb3lus
From (redirected): https://drive.google.com/uc?id=1--fBI59iDhoW67XlevG8kH-vA-mb3lus&confirm=t&uuid=243f3a9e-6b36-49a9-ba21-f9868f1177c5
To: /kaggle/working/model_jp.zip
100%|██████████| 664M/664M [00:10<00:00, 62.1MB/s] 

File berhasil diunduh ke  /kaggle/working/model_jp.zip


In [5]:
!unzip /kaggle/working/model_jp.zip -d /kaggle/working/JP_model
!unzip /kaggle/working/model_sn.zip -d /kaggle/working/SN_model
!unzip /kaggle/working/model_ei.zip -d /kaggle/working/EI_model
!unzip /kaggle/working/model_tf.zip -d /kaggle/working/TF_model

Archive:  /kaggle/working/model_jp.zip
  inflating: /kaggle/working/JP_model/fingerprint.pb  
  inflating: /kaggle/working/JP_model/saved_model.pb  
  inflating: /kaggle/working/JP_model/keras_metadata.pb  
  inflating: /kaggle/working/JP_model/variables/variables.data-00000-of-00001  
  inflating: /kaggle/working/JP_model/variables/variables.index  
  inflating: /kaggle/working/JP_model/assets/vocab.txt  
Archive:  /kaggle/working/model_sn.zip
  inflating: /kaggle/working/SN_model/fingerprint.pb  
  inflating: /kaggle/working/SN_model/saved_model.pb  
  inflating: /kaggle/working/SN_model/keras_metadata.pb  
  inflating: /kaggle/working/SN_model/variables/variables.data-00000-of-00001  
  inflating: /kaggle/working/SN_model/variables/variables.index  
  inflating: /kaggle/working/SN_model/assets/vocab.txt  
Archive:  /kaggle/working/model_ei.zip
   creating: /kaggle/working/EI_model/content/drive/MyDrive/EI_model/
   creating: /kaggle/working/EI_model/content/drive/MyDrive/EI_model/va

In [43]:
model_ei = tf.keras.models.load_model("/kaggle/working/EI_model/content/drive/MyDrive/EI_model")
model_sn = tf.keras.models.load_model("/kaggle/working/SN_model")
model_tf = tf.keras.models.load_model("/kaggle/working/TF_model")
model_jp = tf.keras.models.load_model("/kaggle/working/JP_model")

In [44]:
model_ei._name = 'model_ei'
model_sn._name = 'model_sn'
model_tf._name = 'model_tf'
model_jp._name = 'model_jp'
# model_sn.summary()
# model_tf.summary()

In [45]:
# Load models
def build_classifier_model():
    text_input_ei = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_ei')
    text_input_sn = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_sn')
    text_input_tf = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_tf')
    text_input_jp = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_jp')

    output_ei = model_ei(text_input_ei)
    output_sn = model_sn(text_input_sn)
    output_tf = model_tf(text_input_tf)
    output_jp = model_jp(text_input_jp)

    return tf.keras.Model([text_input_ei,text_input_sn,text_input_tf,text_input_jp], [output_ei,output_sn,output_tf,output_jp])

# Build and summarize the model
model = build_classifier_model()
model.summary()

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text_input_ei (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_sn (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_tf (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_jp (InputLayer)  [(None,)]                    0         []                            
                                                                                            

In [47]:
import numpy as np
EI_text = np.array(['saya suka menyendiri'])
SN_text = np.array(['saya selalu mengikuti kata hati'])
TF_text = np.array(['saya sangat suka melakukakan analisis ketika memutuskan sesuatu'])
JP_text = np.array(['saya suka beradaptasi dengan situasi baru'])
numpy_array = [EI_text,SN_text,TF_text,JP_text]
model.predict(numpy_array)

1/1 [==============================] - 1s 968ms/step


[array([[0.11417162]], dtype=float32),
 array([[0.9435409]], dtype=float32),
 array([[0.00161317]], dtype=float32),
 array([[0.34802148]], dtype=float32)]

In [ ]:
model = build_classifier_model()
model.summary()